"""Exporters turning a fit result into installable configs (SA2).

Ports of upstream generate/gen-filter-chain.py, generalized:

- PipeWire filter-chain: N biquads per channel wired EXPLICITLY (not a
  duplicated mono graph) ending in the LSP limiter_stereo with ``alr`` = 0,
  ``boost`` = 0, ``g_in`` = the fit's linear global gain, ``th`` = 0.891.
  Node prefix configurable (default ``noctalia_audio_tuning``); the target
  sink stays the ``@SPEAKER_SINK@`` placeholder and is substituted at install
  time.
- Omarchy tuning tree: filter-chain.conf + tuning.conf. ``magnitude_rms_db``
  and ``bass_group_delay_swing_ms`` come from the fit; ``limiter_headroom_db``
  and ``dynamic_range_delta_lu`` are POST-INSTALL measurements and are emitted
  as explicit ``not_measured`` markers — never fabricated numbers.
- EasyEffects importable preset JSON (chain of LSP filter processors + the
  global gain as input-gain).
"""
import json
import os

from . import TunerError, fit as fitmod

LIMITER_THRESHOLD = 0.891


def pipewire_filter_chain(sections, linear_gain, prefix="noctalia_audio_tuning",
                          sink="@SPEAKER_SINK@"):
    """Upstream gen-filter-chain.py output, generalized (prefix, sink).

    ``sections`` are (label, freq, q, gain_or_None) bq_* tuples, as returned by
    ``fitmod.parse_fit_text`` / ``fitmod.load_fit``.
    """
    if not sections:
        raise TunerError("bad_fit", "no sections to export")
    nodes, links = [], []
    for ch in ("l", "r"):
        prev = None
        for i, (label, freq, q, g) in enumerate(sections):
            name = f"s{i}_{ch}"
            ctrl = f'"Freq" = {freq} "Q" = {q}'
            if g is not None:
                ctrl += f' "Gain" = {g}'
            nodes.append(f"          {{ type = builtin name = {name:9s} "
                         f"label = {label:12s} control = {{ {ctrl} }} }}")
            if prev:
                links.append(
                    f'          {{ output = "{prev}:Out" input = "{name}:In" }}')
            prev = name
        links.append(
            f'          {{ output = "{prev}:Out" input = "limiter:in_{ch}" }}')
        nodes.append("")

    newline = chr(10)
    return f'''# Speaker tuning generated by noctalia-audio-tuner export.
#
# {len(sections)} biquads per channel followed by a lookahead limiter. Record the
# measurements that justify these values in tuning.conf; see the
# omarchy-audio-tuner README for what a tuning has to report.

context.modules = [
  {{ name = libpipewire-module-filter-chain
    args = {{
      node.description = "Laptop Speakers"
      media.name       = "Laptop Speakers"

      filter.graph = {{
        nodes = [
{newline.join(nodes)}          {{ type   = lv2
            name   = limiter
            plugin = "http://lsp-plug.in/plugins/lv2/limiter_stereo"
            control = {{
              # Both default to enabled: "alr" regulates level toward the
              # threshold and "boost" normalises the threshold up to full
              # scale. A fixed tuning must switch them off or its tone drifts
              # with programme level.
              "alr"   = 0
              "boost" = 0
              # Broadband makeup from the fit, carried by the limiter's input
              # gain so no separate gain stage is needed.
              "g_in"  = {linear_gain}
              "th"    = {LIMITER_THRESHOLD}
            }}
          }}
        ]

        links = [
{newline.join(links)}
        ]

        inputs  = [ "s0_l:In" "s0_r:In" ]
        outputs = [ "limiter:out_l" "limiter:out_r" ]
      }}

      audio.channels = 2
      audio.position = [ FL FR ]

      capture.props = {{
        node.name   = "{prefix}"
        media.class = Audio/Sink
      }}
      playback.props = {{
        node.name     = "{prefix}_output"
        node.passive  = true
        target.object = "{sink}"
      }}
    }}
  }}
]'''


def tuning_conf(magnitude_rms_db, bass_group_delay_swing_ms):
    """tuning.conf text: fit-derived numbers + explicit not_measured markers.

    limiter_headroom_db and dynamic_range_delta_lu are post-install
    measurements; writing a number here would be fabrication.
    """
    return f"""# Tuning report — values written by noctalia-audio-tuner.
#
# From the fit:
magnitude_rms_db = {magnitude_rms_db:.2f}
bass_group_delay_swing_ms = {bass_group_delay_swing_ms:.2f}
#
# Post-installation measurements (run after installing + playing programme):
limiter_headroom_db = not_measured
dynamic_range_delta_lu = not_measured
"""


def easyeffects_preset(sections, gain_db):
    """Importable EasyEffects preset: one LSP `filter` per section.

    The fit's global gain rides ``input-gain`` (EasyEffects clamps it, so the
    payload also reports it under ``noctalia_global_gain_db`` for reference).
    """
    chain = {}
    for i, (label, freq, q, g) in enumerate(sections):
        kind = label.replace("bq_", "")
        filt = {"bypass": False, "kind": kind, "frequency": float(freq),
                "q-factor": float(q), "input-gain": 0.0, "output-gain": 0.0,
                "mode": "RLB (QQ)" if kind in ("lowshelf", "highshelf")
                        else "RLB (QQ)"}
        if g is not None:
            filt["gain"] = float(g)
        chain[f"filter#{i}"] = filt
    return {"output": {
        "blocklist": [],
        "input-gain": round(float(gain_db), 2),
        "output-gain": 0.0,
        **chain,
    }, "input": {"blocklist": []},
        "noctalia_global_gain_db": round(float(gain_db), 2)}


def _fit_from_path(path):
    """Read a fit input file; returns (sections, linear_gain, payload|None)."""
    if not os.path.exists(path):
        raise TunerError("bad_fit", f"no such fit file: {path}")
    with open(path) as fh:
        content = fh.read()
    # A saved fit-result JSON payload takes precedence over upstream text.
    if content.lstrip().startswith("{"):
        try:
            payload = json.loads(content)
            if isinstance(payload, dict) and payload.get("status") == "ok":
                payload = payload["data"]
            if isinstance(payload, dict) and payload.get("sections"):
                return fitmod.load_fit(payload)
        except ValueError:
            pass
    return fitmod.load_fit(content)


def export_pipewire(fit_path, prefix, sink):
    secs, lin, _payload = _fit_from_path(fit_path)
    return {"conf": pipewire_filter_chain(secs, lin, prefix, sink),
            "prefix": prefix, "sink": sink, "n_sections": len(secs),
            "linear_gain": lin}


def export_omarchy(fit_path, prefix, sink, out_dir):
    secs, lin, payload = _fit_from_path(fit_path)
    if payload is not None:
        mag, gd = payload["magnitude_rms_db"], payload["bass_group_delay_swing_ms"]
    else:
        # Text-only input: report fields recomputable from the biquads.
        fs = DEFAULT_EXPORT_RATE
        mag = None
        gd = fitmod.bass_group_delay_swing_ms(
            [(label.replace("bq_", ""), f, q, g if g is not None else 0.0)
             for label, f, q, g in secs], fs)
    if mag is None:
        raise TunerError(
            "bad_fit",
            "omarchy export from a fit.txt has no magnitude_rms_db; "
            "feed the fit-result JSON payload instead")
    conf = pipewire_filter_chain(secs, lin, prefix, sink)
    tconf = tuning_conf(mag, gd)
    os.makedirs(out_dir, exist_ok=True)
    conf_path = os.path.join(out_dir, "filter-chain.conf")
    tconf_path = os.path.join(out_dir, "tuning.conf")
    with open(conf_path, "w") as fh:
        fh.write(conf + "\n")
    with open(tconf_path, "w") as fh:
        fh.write(tconf)
    return {"out_dir": os.path.abspath(out_dir), "prefix": prefix, "sink": sink,
            "filter_chain_conf": conf_path, "tuning_conf": tconf_path,
            "n_sections": len(secs), "linear_gain": lin,
            "magnitude_rms_db": mag, "bass_group_delay_swing_ms": gd,
            "conf": conf, "tuning_conf_text": tconf}


def export_easyeffects(fit_path, out_path=None):
    secs, lin, payload = _fit_from_path(fit_path)
    gain_db = payload["global_gain_db"] if payload else 20 * _log10(lin)
    preset = easyeffects_preset(secs, gain_db)
    wrote = None
    if out_path:
        os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
        with open(out_path, "w") as fh:
            json.dump(preset, fh, indent=2)
            fh.write("\n")
        wrote = os.path.abspath(out_path)
    return {"preset": preset, "out": wrote, "n_sections": len(secs),
            "global_gain_db": gain_db}


DEFAULT_EXPORT_RATE = 48000


def _log10(x):
    import math
    return math.log10(x)
